#! /bin/bash

RELEASE=$(lsb_release -c|sed 's/.*:\t//g')

cd /root
wget "http://apt.puppetlabs.com/puppetlabs-release-$RELEASE.deb"
dpkg -i "puppetlabs-release-$RELEASE.deb"
rm -f "puppetlabs-release-$RELEASE.deb"
apt-get update && apt-get install -y puppet
apt-get install -y make ruby1.9.1 ruby1.9.1-dev
gem install librarian-puppet

BOOTSTRAP=$(facter ck99_bootstrap)/support/puppet
puppet apply $BOOTSTRAP/manifests/bootstrap-puppet.pp --hiera_config $BOOTSTRAP/hiera.yaml

cd /etc/puppet
librarian-puppet install
puppet apply manifests/site.pp
